apiVersion: v1
kind: ConfigMap
metadata:
  name: article-config
data:
  ARTICLE_DB_HOST: "192.168.60.250"
  ARTICLE_DB_PORT: "6033"
  ARTICLE_DB_USERNAME: "article_user"
  REDIS_MASTER_NAME: "mymaster"
  SPRING_DATA_REDIS_SENTINEL_NODES: "192.168.60.131:26379,192.168.60.231:26379,192.168.40.131:26379,192.168.40.231:26379"
  SPRING_DATA_REDIS_SENTINEL_MASTER: "mymaster"
  IMG_PATH: "https://santalog-s3.s3.ap-northeast-2.amazonaws.com/img/"
  JWT_ISSUER: "santa-log-developer"
  SPRING_MAIN_SERVER_FORWARD-HEADERS-STRATEGY: "NATIVE"