apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: santalog-article-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: santalog.cloud
      http:
        paths:
          - path: /article
            pathType: Prefix
            backend:
              service:
                name: article-service
                port:
                  number: 80 # Service의 port(80)와 일치시킴