apiVersion: v1
kind: Service
metadata:
  name: article-service
spec:
  type: NodePort
  selector:
    app: santa-article
  ports:
    - port: 80         # Cluster 내부용 포트
      targetPort: 8081 # Pod 포트
      nodePort: 30081  # VIP/외부 접근용 NodePort
