apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: santalog-auth
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://10.106.205.245:3306/auth_db?connectTimeout=5000&socketTimeout=60000
  SPRING_DATASOURCE_USERNAME: app_user

  JWT_ISSUER: santa-log-developer
  REDIS_MASTER_NAME: mymaster
  REDIS_NODE1: 192.168.60.131:26379
  REDIS_NODE2: 192.168.60.231:26379
  REDIS_NODE3: 192.168.40.131:26379
  REDIS_NODE4: 192.168.40.231:26379
