apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: santalog-auth
data:
  AUTH_DB_HOST: "10.106.205.245"
  AUTH_DB_PORT: "3306"
  AUTH_DB_USERNAME: "app_user"
  JWT_ISSUER: "santa-log-developer"
  REDIS_MASTER_NAME: "mymaster"
  SPRING_DATA_REDIS_SENTINEL_NODES: "192.168.60.131:26379,192.168.60.231:26379,192.168.40.131:26379,192.168.40.231:26379"
  SPRING_DATA_REDIS_SENTINEL_MASTER: "mymaster"
  SPRING_MAIN_SERVER_FORWARD-HEADERS-STRATEGY: "NATIVE"
  SERVER_TOMCAT_REMOTEIP_PROTOCOL-HEADER: "x-forwarded-proto"
  SPRING_JPA_PROPERTIES_HIBERNATE_GLOBALLY_QUOTED_IDENTIFIERS: "true"
  SPRING_JPA_SHOW-SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"