apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: santalog-auth-ingress
  namespace: santalog-auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-cookie-domain: "auth-service santalog.cloud"
    nginx.ingress.kubernetes.io/proxy-cookie-path: "/ /"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Port 31443;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      proxy_cookie_flags ~ "SameSite=None; Secure";
spec:
  rules:
    - host: santalog.cloud
      http:
        paths:
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /signup
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /api/token
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /auth/admin
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80