apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: santalog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: santalog.cloud
      http:
        paths:
          # Auth Service
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8080

          # Article Service
          - path: /article
            pathType: Prefix
            backend:
              service:
                name: article-service
                port:
                  number: 8080
