name: Build & Push Article Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'santaLog-article/**'
      - 'k8s/**'
      - '.github/workflows/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build article jar
        run: ./gradlew :santaLog-article:bootJar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push article image
        uses: docker/build-push-action@v5
        with:
          context: santaLog-article
          file: santaLog-article/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/santa-article:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/santa-article:latest

      # ---------------- CD ----------------

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      - name: Create or Update Article Secret
        run: |
          kubectl create secret generic article-secret \
            --from-literal=JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            --from-literal=REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Article ConfigMap
        run: kubectl apply -f k8s/configmaps/article-configmap.yaml

      - name: Deploy Article to Kubernetes
        run: |
          kubectl apply -f k8s/deployments/article-deploy.yaml
          kubectl apply -f k8s/services/article-service.yaml
          kubectl set image deployment/santa-article \
            article-container=${{ secrets.DOCKERHUB_USERNAME }}/santa-article:${{ github.sha }}
